/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.robotproject.xtextdsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.unice.polytech.robotproject.xtextdsl.ide.contentassist.antlr.internal.InternalMyDSLParser;
import fr.unice.polytech.robotproject.xtextdsl.services.MyDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MyDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getRobotAccess().getGroup(), "rule__Robot__Group__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_3(), "rule__Robot__Group_3__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_3_3(), "rule__Robot__Group_3_3__0");
			builder.put(grammarAccess.getMoveStraightAccess().getGroup(), "rule__MoveStraight__Group__0");
			builder.put(grammarAccess.getTurnAccess().getGroup(), "rule__Turn__Group__0");
			builder.put(grammarAccess.getDurationAccess().getGroup(), "rule__Duration__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getRobotAccess().getInstructionsAssignment_3_2(), "rule__Robot__InstructionsAssignment_3_2");
			builder.put(grammarAccess.getRobotAccess().getInstructionsAssignment_3_3_1(), "rule__Robot__InstructionsAssignment_3_3_1");
			builder.put(grammarAccess.getMoveStraightAccess().getAmountAssignment_1(), "rule__MoveStraight__AmountAssignment_1");
			builder.put(grammarAccess.getMoveStraightAccess().getDurationAssignment_2(), "rule__MoveStraight__DurationAssignment_2");
			builder.put(grammarAccess.getTurnAccess().getAmountAssignment_1(), "rule__Turn__AmountAssignment_1");
			builder.put(grammarAccess.getTurnAccess().getDurationAssignment_2(), "rule__Turn__DurationAssignment_2");
			builder.put(grammarAccess.getAmountAccess().getValueAssignment(), "rule__Amount__ValueAssignment");
			builder.put(grammarAccess.getDurationAccess().getValueAssignment_1(), "rule__Duration__ValueAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDSLGrammarAccess grammarAccess;

	@Override
	protected InternalMyDSLParser createParser() {
		InternalMyDSLParser result = new InternalMyDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
