/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.robotproject.xtextdsl.ide


/**
 * Use this class to register ide components.
 */
class MyDslIdeModule extends AbstractMyDslIdeModule {
}
