/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.robotproject


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RobotdslStandaloneSetup extends RobotdslStandaloneSetupGenerated {

	def static void doSetup() {
		new RobotdslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
