/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.robotproject.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobotdslScopeProvider extends DelegatingScopeProvider {
}
