/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.robotproject.serializer;

import com.google.inject.Inject;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Move;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Robot;
import fr.unice.polytech.robotproject.model.RobotProjectModel.RobotProjectModelPackage;
import fr.unice.polytech.robotproject.services.RobotdslGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class RobotdslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private RobotdslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RobotProjectModelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RobotProjectModelPackage.MOVE:
				sequence_Move(context, (Move) semanticObject); 
				return; 
			case RobotProjectModelPackage.ROBOT:
				sequence_Robot(context, (Robot) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Instruction returns Move
	 *     Move returns Move
	 *
	 * Constraint:
	 *     distance=EInt?
	 */
	protected void sequence_Move(ISerializationContext context, Move semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Robot returns Robot
	 *
	 * Constraint:
	 *     (instructions+=Instruction instructions+=Instruction*)?
	 */
	protected void sequence_Robot(ISerializationContext context, Robot semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
