/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.robotproject.xtextdsl.serializer;

import com.google.inject.Inject;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Angle;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Call;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Distance;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Duration;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Function;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Grab;
import fr.unice.polytech.robotproject.model.RobotProjectModel.If;
import fr.unice.polytech.robotproject.model.RobotProjectModel.MoveStraight;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Release;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Robot;
import fr.unice.polytech.robotproject.model.RobotProjectModel.RobotProjectModelPackage;
import fr.unice.polytech.robotproject.model.RobotProjectModel.SensorActivation;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Turn;
import fr.unice.polytech.robotproject.model.RobotProjectModel.Wait;
import fr.unice.polytech.robotproject.xtextdsl.services.MyDslGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RobotProjectModelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RobotProjectModelPackage.ANGLE:
				sequence_Angle(context, (Angle) semanticObject); 
				return; 
			case RobotProjectModelPackage.CALL:
				sequence_Call(context, (Call) semanticObject); 
				return; 
			case RobotProjectModelPackage.DISTANCE:
				sequence_Distance(context, (Distance) semanticObject); 
				return; 
			case RobotProjectModelPackage.DURATION:
				sequence_Duration(context, (Duration) semanticObject); 
				return; 
			case RobotProjectModelPackage.FUNCTION:
				if (rule == grammarAccess.getFunctionRule()) {
					sequence_Function(context, (Function) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getInstructionRule()
						|| rule == grammarAccess.getInstructionBlockRule()) {
					sequence_Function_InstructionBlock(context, (Function) semanticObject); 
					return; 
				}
				else break;
			case RobotProjectModelPackage.GRAB:
				sequence_Grab(context, (Grab) semanticObject); 
				return; 
			case RobotProjectModelPackage.IF:
				if (rule == grammarAccess.getIfRule()) {
					sequence_If(context, (If) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getInstructionRule()
						|| rule == grammarAccess.getInstructionBlockRule()) {
					sequence_If_InstructionBlock(context, (If) semanticObject); 
					return; 
				}
				else break;
			case RobotProjectModelPackage.MOVE_STRAIGHT:
				sequence_MoveStraight(context, (MoveStraight) semanticObject); 
				return; 
			case RobotProjectModelPackage.RELEASE:
				sequence_Release(context, (Release) semanticObject); 
				return; 
			case RobotProjectModelPackage.ROBOT:
				sequence_Robot(context, (Robot) semanticObject); 
				return; 
			case RobotProjectModelPackage.SENSOR_ACTIVATION:
				sequence_SensorActivation(context, (SensorActivation) semanticObject); 
				return; 
			case RobotProjectModelPackage.TURN:
				sequence_Turn(context, (Turn) semanticObject); 
				return; 
			case RobotProjectModelPackage.WAIT:
				sequence_Wait(context, (Wait) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Angle returns Angle
	 *
	 * Constraint:
	 *     (value=EInt angleUnit=AngleUnit?)
	 */
	protected void sequence_Angle(ISerializationContext context, Angle semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Call
	 *     Call returns Call
	 *
	 * Constraint:
	 *     destination=[Function|EString]
	 */
	protected void sequence_Call(ISerializationContext context, Call semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotProjectModelPackage.Literals.CALL__DESTINATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotProjectModelPackage.Literals.CALL__DESTINATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCallAccess().getDestinationFunctionEStringParserRuleCall_1_0_1(), semanticObject.eGet(RobotProjectModelPackage.Literals.CALL__DESTINATION, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Distance returns Distance
	 *
	 * Constraint:
	 *     (value=EInt distanceUnit=DistanceUnit)
	 */
	protected void sequence_Distance(ISerializationContext context, Distance semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotProjectModelPackage.Literals.AMOUNT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotProjectModelPackage.Literals.AMOUNT__VALUE));
			if (transientValues.isValueTransient(semanticObject, RobotProjectModelPackage.Literals.DISTANCE__DISTANCE_UNIT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotProjectModelPackage.Literals.DISTANCE__DISTANCE_UNIT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDistanceAccess().getValueEIntParserRuleCall_0_0(), semanticObject.getValue());
		feeder.accept(grammarAccess.getDistanceAccess().getDistanceUnitDistanceUnitEnumRuleCall_1_0(), semanticObject.getDistanceUnit());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Duration returns Duration
	 *
	 * Constraint:
	 *     (value=EInt timeUnit=TimeUnit)
	 */
	protected void sequence_Duration(ISerializationContext context, Duration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotProjectModelPackage.Literals.AMOUNT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotProjectModelPackage.Literals.AMOUNT__VALUE));
			if (transientValues.isValueTransient(semanticObject, RobotProjectModelPackage.Literals.DURATION__TIME_UNIT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotProjectModelPackage.Literals.DURATION__TIME_UNIT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDurationAccess().getValueEIntParserRuleCall_0_0(), semanticObject.getValue());
		feeder.accept(grammarAccess.getDurationAccess().getTimeUnitTimeUnitEnumRuleCall_1_0(), semanticObject.getTimeUnit());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Function
	 *
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_Function(ISerializationContext context, Function semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotProjectModelPackage.Literals.FUNCTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotProjectModelPackage.Literals.FUNCTION__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFunctionAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Function
	 *     InstructionBlock returns Function
	 *
	 * Constraint:
	 *     (name=EString (instructions+=Instruction instructions+=Instruction*)?)
	 */
	protected void sequence_Function_InstructionBlock(ISerializationContext context, Function semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Grab
	 *     Grab returns Grab
	 *
	 * Constraint:
	 *     {Grab}
	 */
	protected void sequence_Grab(ISerializationContext context, Grab semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     If returns If
	 *
	 * Constraint:
	 *     condition=Condition?
	 */
	protected void sequence_If(ISerializationContext context, If semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns If
	 *     InstructionBlock returns If
	 *
	 * Constraint:
	 *     (condition=Condition? (instructions+=Instruction instructions+=Instruction*)?)
	 */
	protected void sequence_If_InstructionBlock(ISerializationContext context, If semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns MoveStraight
	 *     TimedInstruction returns MoveStraight
	 *     MoveStraight returns MoveStraight
	 *
	 * Constraint:
	 *     (distance=Distance duration=Duration?)
	 */
	protected void sequence_MoveStraight(ISerializationContext context, MoveStraight semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Release
	 *     Release returns Release
	 *
	 * Constraint:
	 *     {Release}
	 */
	protected void sequence_Release(ISerializationContext context, Release semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Robot returns Robot
	 *
	 * Constraint:
	 *     (instructions+=Instruction instructions+=Instruction*)?
	 */
	protected void sequence_Robot(ISerializationContext context, Robot semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Condition returns SensorActivation
	 *     SensorActivation returns SensorActivation
	 *
	 * Constraint:
	 *     {SensorActivation}
	 */
	protected void sequence_SensorActivation(ISerializationContext context, SensorActivation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Turn
	 *     TimedInstruction returns Turn
	 *     Turn returns Turn
	 *
	 * Constraint:
	 *     (angle=Angle duration=Duration?)
	 */
	protected void sequence_Turn(ISerializationContext context, Turn semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Wait
	 *     TimedInstruction returns Wait
	 *     Wait returns Wait
	 *
	 * Constraint:
	 *     duration=Duration?
	 */
	protected void sequence_Wait(ISerializationContext context, Wait semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
