/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.robotproject.ui;

import com.google.inject.Injector;
import fr.unice.polytech.robotproject.robotdsl.ui.internal.RobotdslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RobotdslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RobotdslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RobotdslActivator activator = RobotdslActivator.getInstance();
		return activator != null ? activator.getInjector(RobotdslActivator.FR_UNICE_POLYTECH_ROBOTPROJECT_ROBOTDSL) : null;
	}

}
