/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.robotproject.ui.tests;

import com.google.inject.Injector;
import fr.unice.polytech.robotproject.robotdsl.ui.internal.RobotdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RobotdslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RobotdslActivator.getInstance().getInjector("fr.unice.polytech.robotproject.Robotdsl");
	}

}
